# render.yaml
services:
  - type: web
    name: tennis-app
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn wsgi:app
    envVars:
      - key: SUPABASE_URL
        value: https://bpjwoqsphnjroqpkutji.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwandvcXNwaG5qcm9xcGt1dGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODEwNzQsImV4cCI6MjA1OTI1NzA3NH0.hW7mKqGmXG0nTeBxjgHMhVVqaE2AFcC-kPnGAp_IceM

  # Опционально: Cron для очистки очереди
  - type: cron
    name: daily-cleanup
    schedule: "0 0 * * *"
    buildCommand: ""
    runCommand: |
      curl -X POST \
      -H "apikey: $SUPABASE_KEY" \
      -H "Content-Type: application/json" \
      -d '{ "query": "UPDATE queues SET status = ''left'' WHERE created_at < NOW() - INTERVAL ''1 day''" }' \
      "$SUPABASE_URL/rest/v1/rpc/execute"
